name: take_it
description: Scoped Service Locator with Constructor Injections for Dart and Flutter.
version: 1.0.2

repository: https://github.com/tekmates/take_it
homepage: https://github.com/tekmates/take_it
issue_tracker: https://github.com/tekmates/take_it/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - di-framework
  - ioc
  - service-locator
  - dependency-injection
  - clean-architecture

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # For tests only
  get_it: 7.7.0
  equatable: ^2.0.5
